### ISSUE TITLE
"Unexpected token {" when using `npm build run`

### ISSUE THREAD

**Issue by jgraup** [kadamwhite/wp-notebook#1]
I'm seeing this error from multiple machines; `SyntaxError: Unexpected token {`

Is there something you need to do prior `npm build run` other than `npm install`?

Thanks

```
~/workspace/wp-content/plugins/wp-notebook (master) $ npm run build
> wp-notebook@1.0.0 build /home/ubuntu/workspace/wp-content/plugins/wp-notebook
> webpack
/home/ubuntu/workspace/wp-content/plugins/wp-notebook/webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { const { resolve } = require('path');
                                                                    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/ubuntu/workspace/wp-content/plugins/wp-notebook/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/ubuntu/workspace/wp-content/plugins/wp-notebook/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
npm ERR! Linux 4.8.2-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "run" "build"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! wp-notebook@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-notebook@1.0.0 build script 'webpack'.
npm ERR! This is most likely a problem with the wp-notebook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wp-notebook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wp-notebook
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/wp-content/plugins/wp-notebook/npm-debug.log
```

**Comment by kadamwhite** [comment]
@jgraup Thank you for the issue, sorry I missed the notification when you opened it. May I ask what version of Node you are using?

**Comment by kadamwhite** [comment]
@jgraup I realize I missed seeing the 4.6.1 node version in your error trace; apologies for that. I recommend using Node 6 to build this project, the destructuring syntax used in the config is not available in Node 4.
